# Generated by Django 3.1.7 on 2021-03-03 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('team_name', models.CharField(max_length=30)),
                ('captain', models.CharField(max_length=30)),
                ('vice_captain', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Permanent Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamEvents',
            fields=[
                ('tevent_id', models.AutoField(primary_key=True, serialize=False)),
                ('events', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Team Events',
            },
        ),
        migrations.CreateModel(
            name='TeamRegistrationmodel',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField(default=2021)),
                ('category', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('team_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Team Registration',
            },
        ),
        migrations.CreateModel(
            name='TeamRecordModel',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('score_team1', models.CharField(blank=True, max_length=30)),
                ('score_team2', models.CharField(blank=True, max_length=30)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictionapp.teamevents')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='predictionapp.teamregistrationmodel')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='predictionapp.teamregistrationmodel')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team3', to='predictionapp.teamregistrationmodel')),
            ],
            options={
                'verbose_name_plural': 'Team Records',
            },
        ),
        migrations.CreateModel(
            name='TeamPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictionapp.permanentteam')),
            ],
            options={
                'verbose_name_plural': 'Team Players',
            },
        ),
        migrations.AddField(
            model_name='permanentteam',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictionapp.teamevents'),
        ),
    ]
