# Generated by Django 3.1.7 on 2021-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
