# Generated by Django 3.1.7 on 2021-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0002_auto_20210303_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistrationmodel',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
