# Generated by Django 3.1.7 on 2021-03-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0003_auto_20210303_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistrationmodel',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictionapp.permanentteam'),
        ),
        migrations.AlterField(
            model_name='teamregistrationmodel',
            name='year',
            field=models.DateField(default=2021),
        ),
    ]
