# Generated by Django 3.1.7 on 2021-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0005_auto_20210303_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayers',
            name='id_number',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
