# Generated by Django 3.1.7 on 2021-03-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0006_teamplayers_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamregistrationmodel',
            old_name='teamid',
            new_name='reg_id',
        ),
    ]
    atomic = False

